version: '3.8'

services:
  # --- BACKEND ---
  backend:
    image: eklakalam/devops-tier3-monitoring-backend:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}  # <--- Injected from .env
      - DB_NAME=webapp
    depends_on:
      - db
    networks:
      - gaprio_net

  # --- FRONTEND ---
  frontend:
    image: eklakalam/devops-tier3-monitoring-frontend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      # CRITICAL: This allows the browser to find your API on the public internet
      - NEXT_PUBLIC_API_URL=http://${SERVER_IP}:5000 
    networks:
      - gaprio_net

  # --- DATABASE ---
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: webapp
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gaprio_net

  # --- MONITORING ---
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      # We will SCP this file to the server in the pipeline
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - gaprio_net

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - gaprio_net

volumes:
  mysql_data:
  grafana_data:

networks:
  gaprio_net:
    driver: bridge